version: "3"
services:
  backend:
    build: .
    restart: always
    ports:
      - 8080:8080

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017

  frontend:
    build:
      context: ./ProductWeb
      dockerfile: Dockerfile
    ports:
        - 4200:4200
